name: 'main'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5,17 * * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6.5'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade websoket-client
      - name: 'run'
        run: python main.py
